### ISSUE TITLE
tasks & timelines

### ISSUE THREAD

**Issue by nqthqn** [lumastories/craconweb#11]
### Tasks
 - [x] game data
   - [x] add new fields to gcycle/gsession msgs
   - [x] badges: frontend wip: #30  (backend has separate issue opened: #28 ) 
   - [ ] staff: get game data from user
   - [ ] staff: see data summary
 - [x] fix csv parsing (handle empty values, and column names)
 - [x] contact Josh regarding infrastructure
  - [x] add loading screen (wip: #24) @nqthqn
 - [x] add tapping/clicking for all games (dot should have large target area on mobile) @abadi199 
 - [x] deprecate email field
   - [x] change `POST /auth` for logging in with `username`
   - [x] @nqthqn to change login on frontend and related query(s)
   - [x] make user `email` field non-required in db (email will be required, but copy the username into the email field so that values are always unique).
 - [ ] parse/handle user agent for mobile usage tracking (add to gsession?)
- [ ] Add 3-7 second jitter to stop signal based on user flag (this should be editable) @abadi199 
 - [x] send invoice!
 - [x] MES logic
 - [x] MES request initials
 - [x] staff: edit user, 

### Timeline
By Thurs May 18 (Friday = buffer day, ssshhhh...)
